Repository choderalab/perses, pull requests merged in 2022-06, with the labels that each got.

#992 Update HybridCompatibilityMixin to handle RESTCapableHybridTopologyFactory and add repex self-consistency tests
  perses/annihilation/relative.py
  perses/data/arg_solvated.cif
  perses/data/lys_solvated.cif
  perses/data/thr_vacuum.pdb
  perses/samplers/multistate.py
  perses/tests/test_repex.py
  perses/tests/test_samplers.py
  perses/tests/test_smc.py
Labels: priority: medium

#1037 unsampled endstates long range correction as an input yaml option
  docs/changelog.rst
  examples/protein-ligand/cli/protein-ligand.yaml
  perses/app/setup_relative_calculation.py
Labels: enhancement :sparkles:

#1030 Add option to control whether water is alchemically changed into counterion for charge changes
  perses/app/fah_generator.py
  perses/app/relative_point_mutation_setup.py
  perses/app/relative_setup.py
  perses/app/setup_relative_calculation.py
  perses/tests/test_relative_point_mutation_setup.py
Labels: priority: high

#1046 Fix cutoff and lifting parameters in `RESTCapableHybridTopologyFactory`
  perses/annihilation/relative.py
  perses/app/relative_point_mutation_setup.py
  perses/app/setup_relative_calculation.py
Labels: bug :bug:, priority: high
